import { buildScenario } from './experiments/scenarios.ts';
import { InlineRuntime } from './runtime/InlineRuntime.ts';
import { Simulation } from './runtime/Simulation.ts';
const rt = new InlineRuntime();
const sim = new Simulation(buildScenario({ name: 'S4', robots: 5, fault: 'none' }, 'baseline', 1), rt);
rt.initSync(sim.agentConfigs());
const orig = rt.stepSync.bind(rt);
let last: any[] = [];
rt.stepSync = (obs) => { const a = orig(obs); last = a.map((x, i) => ({ k: x?.kind, d: x?.dir, ind: x?.indicator, obs: obs[i] && { rob: obs[i]!.robots.map(r=>[r.id,r.cell,r.indicator,r.moving]), selfInd: obs[i]!.self.indicator } })); return a; };
for (let i = 0; i < 8000; i++) sim.tickSync();
console.log(sim.grid.idx(1,12), JSON.stringify(last[0]), JSON.stringify(last[4]));
